<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Base' => $vendorDir . '/krokedil/woocommerce/src/Base.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\Cart' => $vendorDir . '/krokedil/woocommerce/src/Cart/Cart.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartCustomer' => $vendorDir . '/krokedil/woocommerce/src/Cart/CartCustomer.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineCoupon' => $vendorDir . '/krokedil/woocommerce/src/Cart/CartLineCoupon.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineFee' => $vendorDir . '/krokedil/woocommerce/src/Cart/CartLineFee.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineItem' => $vendorDir . '/krokedil/woocommerce/src/Cart/CartLineItem.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineShipping' => $vendorDir . '/krokedil/woocommerce/src/Cart/CartLineShipping.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Abstracts\\AbstractGiftCardCompatibility' => $vendorDir . '/krokedil/woocommerce/src/Compatibility/Abstracts/AbstractGiftCardCompatibility.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Compatibility' => $vendorDir . '/krokedil/woocommerce/src/Compatibility/Compatibility.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\PWGiftCards' => $vendorDir . '/krokedil/woocommerce/src/Compatibility/Giftcards/PWGiftCards.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\SmartCoupons' => $vendorDir . '/krokedil/woocommerce/src/Compatibility/Giftcards/SmartCoupons.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\WCGiftCards' => $vendorDir . '/krokedil/woocommerce/src/Compatibility/Giftcards/WCGiftCards.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\YITHGiftCards' => $vendorDir . '/krokedil/woocommerce/src/Compatibility/Giftcards/YITHGiftCards.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\CustomerData' => $vendorDir . '/krokedil/woocommerce/src/CustomerData.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\CompatibilityInterface' => $vendorDir . '/krokedil/woocommerce/src/Interfaces/CompatibilityInterface.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\GiftCardCompatibilityInterface' => $vendorDir . '/krokedil/woocommerce/src/Interfaces/GiftCardCompatibilityInterface.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\MetaboxInterface' => $vendorDir . '/krokedil/woocommerce/src/Interfaces/MetaboxInterface.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\KrokedilWooCommerce' => $vendorDir . '/krokedil/woocommerce/src/KrokedilWooCommerce.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\OrderData' => $vendorDir . '/krokedil/woocommerce/src/OrderData.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\OrderLineData' => $vendorDir . '/krokedil/woocommerce/src/OrderLineData.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\OrderMetabox' => $vendorDir . '/krokedil/woocommerce/src/OrderMetabox.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\OrderUtility' => $vendorDir . '/krokedil/woocommerce/src/OrderUtility.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Order\\Order' => $vendorDir . '/krokedil/woocommerce/src/Order/Order.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderCustomer' => $vendorDir . '/krokedil/woocommerce/src/Order/OrderCustomer.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLine' => $vendorDir . '/krokedil/woocommerce/src/Order/OrderLine.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineCoupon' => $vendorDir . '/krokedil/woocommerce/src/Order/OrderLineCoupon.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineFee' => $vendorDir . '/krokedil/woocommerce/src/Order/OrderLineFee.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineItem' => $vendorDir . '/krokedil/woocommerce/src/Order/OrderLineItem.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineShipping' => $vendorDir . '/krokedil/woocommerce/src/Order/OrderLineShipping.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApi' => $vendorDir . '/krokedil/woocommerce/src/StoreApi/StoreApi.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiCustomer' => $vendorDir . '/krokedil/woocommerce/src/StoreApi/StoreApiCustomer.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineCoupon' => $vendorDir . '/krokedil/woocommerce/src/StoreApi/StoreApiLineCoupon.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineFee' => $vendorDir . '/krokedil/woocommerce/src/StoreApi/StoreApiLineFee.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineItem' => $vendorDir . '/krokedil/woocommerce/src/StoreApi/StoreApiLineItem.php',
    'KrokedilNexiCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineShipping' => $vendorDir . '/krokedil/woocommerce/src/StoreApi/StoreApiLineShipping.php',
);
